version: "3"

networks:
  mysql:
    name: ${DB_CONTAINER:-mysql}

volumes:
  mysql_data:
    name: ${DB_CONTAINER:-mysql}

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${DB_CONTAINER:-mysql}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_USER=${DB_USERNAME:-yourusername}
      - MYSQL_PASSWORD=${DB_PASSWORD:-yoursecret}
      - MYSQL_DATABASE=${DB_DATABASE:-yourdatabase}
    ports:
      - 3307:3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql
