version: "3"

volumes:
  mongo:
    name: ${DB_CONTAINER:-mongo}

services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-mongo}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-mongo}
