version: "3"

networks:
  postgres:
    name: ${DB_CONTAINER:-postgres}

volumes:
  db:
    name: ${DB_CONTAINER:-postgres}

services:
  postgres:
    image: postgres:alpine
    container_name: ${DB_CONTAINER:-postgres}
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
      - POSTGRES_DB=${DB_DATABASE:-postgres}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

  pgweb:
    image: "sosedoff/pgweb"
    container_name: pgweb
    ports:
      - "8082:8081"
    networks:
      - postgres
    environment:
      - SESSIONS=1
      - LOCK_SESSION=TRUE
      - DATABASE_URL=postgres://${DB_USERNAME:-postgres}:${DB_PASSWORD:-secret}@${DB_CONTAINER:-postgres}:5432/${DB_DATABASE:-postgres}?sslmode=disable
    depends_on:
      - postgres
