version: "3"

volumes:
  sql-server:
    name: ${DB_CONTAINER:-mssql}

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=${DB_PASSWORD:-password}
      - ACCEPT_EULA=Y
    volumes:
      - sql-server:/var/opt/mssql
